spring.application.name=auth
server.port=8082
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://localhost:3306/LOCATION
spring.datasource.username=root
spring.datasource.password=akligo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false


# Mailing (MailDev)
# =======================
# spring.mail.host=localhost
# spring.mail.port=1025
# spring.mail.username=
# spring.mail.password=
# spring.mail.properties.mail.smtp.auth=false
# spring.mail.properties.mail.smtp.starttls.enable=false
# spring.mail.properties.mail.debug=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=koffitsejeromea@gmail.com
spring.mail.password=fwbn jlgk wlex uahu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.from=Location-Appartements-Vehicules


spring.main.allow-circular-references=true
logging.level.org.springframework=DEBUG

# Frontend activation URL
mailing.frontend.activation-url=http://localhost:4200/activate-account

# Email de réception des messages de contact
contact.email.recipient=koffitsejeromea@gmail.com

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

#paiment gateway
#payment.gateway.api-key=0f4b917b-4923-4bbb-9071-24be4dfedb1f